[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = 'let g:vim_json_syntax_conceal = 0'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  " Width (default 40)
  let g:tagbar_width = 40
  " Map for toggle
  nnoremap <silent><nowait> ss :TagbarToggle<cr>
'''

# [[plugins]]
# repo = 'plasticboy/vim-markdown'
# on_ft = ['markdown','mkd', 'md']
#  hook_add = '''
#    let g:vim_markdown_folding_disabled = 1
#  '''

# quote内のプログラムをシンタックスハイライトする
[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown']

# [[plugins]]
# repo = 'beanworks/vim-phpfmt'
# on_ft = ['php']
# hook_add = '''
#   "let g:phpfmt_standard = "PSR2"
#   let g:phpfmt_standard = '~/.config/php/c-psr2.xml'
# '''

# [[plugins]]
# repo = 'vim-vdebug/vdebug'
# on_ft = ['php']
# hook_add = '''
#   let g:vdebug_options= {
#   \    'on_close': "detach",
#   \    'break_on_open': 0
#   \}
# '''

[[plugins]]
repo = "puremourning/vimspector"
on_ft = ["python", "javascript", "sh", "php"]
build = "./install_gadget.py --enable-python --force-enable-node --enable-bash --force-enable-php"
hook_add = '''
  let g:vimspector_enable_mappings = 'VISUAL_STUDIO'
  " for normal mode - the word under the cursor
  nmap <Leader>di <Plug>VimspectorBalloonEval
  " for visual mode, the visually selected text
  xmap <Leader>di <Plug>VimspectorBalloonEval
  let g:vimspector_sidebar_width = 65
  nmap <Leader>db <Plug>VimspectorBreakpoints
  let g:vimspector_sign_priority = {
    \    'vimspectorBP':         11,
    \    'vimspectorBPCond':     11,
    \    'vimspectorBPLog':      11,
    \    'vimspectorBPDisabled': 11,
    \    'vimspectorPC':         11,
    \ }
  sign define vimspectorBP text=🔴 texthl=Normal
  sign define vimspectorBPDisabled text=🔵 texthl=Normal
  sign define vimspectorPC text=🔶 texthl=SpellBad
'''
