command_timeout = 1000

[cmd_duration]
disabled = true

[package]
disabled = true

[docker_context]
disabled = true

[vagrant]
disabled = true

[directory]
truncation_length = 100
truncate_to_repo = false

